# List of items that can be dropped by breaking stone
drops:
  EMERALD:
    chance: 0.8
    displayName: "Szmaragd"
  DIAMOND:
    chance: 1.0
    displayName: "Diament"
  IRON_INGOT:
    chance: 2.0
    displayName: "Zelazo"
  GOLD_INGOT:
    chance: 1.2
    displayName: "Zloto"
  REDSTONE:
    chance: 1.7
    displayName: "Redstone"
  LAPIS_LAZULI:
    chance: 1.7
    displayName: "Lapis"
  COAL:
    chance: 2.5
    displayName: "Wegiel"
  NETHERITE_INGOT:
    chance: 0.1
    displayName: "Netherite"
# World where plugin is enabled
world: "world"
# Multiplier for drop chance per island levels
drop_multiplier_per_island_level:
  levels_interval: 250
  multiplier_value: 0.01
# Amount of exp dropped by breaking stone
stone_exp_drop: 1
# Database connection settings (SQLite/MySQL)
database:
  type: "SQLite"
# Uncomment below lines to use MySQL database
#  host: "localhost"
#  port: 3306
#  name: "xlucashdrop_db"
#  username: "root"
#  password: ""